language: dart

dart:
  - preview/raw/2.10.0-0.2-dev

dart_task:
  - test: --platform vm,chrome
  - dartfmt
  - dartanalyzer: --fatal-warnings --fatal-hints .

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
